name: Vorpal SAST Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  vorpal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug workspace
        run: |
          echo "Current directory:"
          pwd
          echo "Files in workspace:"
          ls -R

      - name: Run Vorpal Scan
        uses: checkmarx/vorpal-reviewdog-github-action@v1.0.0

      - name: Show Vorpal results
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_path: "server.js"
          level: error
          reporter: github-pr-check

      - name: Show Vorpal results
        run: |
          echo "===== VORPAL RESULTS ====="
          cat result.errorformat
